
package javaapplication14;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class JDBFrame extends javax.swing.JFrame {
  
    public JDBFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddName = new javax.swing.JLabel();
        jAddedName = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jAddedAge = new javax.swing.JLabel();
        jTexAddedAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSelect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));

        jAddName.setText("name");

        jAddedName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddedNameMouseClicked(evt);
            }
        });
        jAddedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddedNameActionPerformed(evt);
            }
        });

        jButtonInsert.setText("insert");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertAction(evt);
            }
        });

        jAddedAge.setText("Age");

        jTexAddedAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexAddedAgeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSelect.setText("select");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddedAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTexAddedAge, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAddedName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddName)
                    .addComponent(jAddedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddedAge)
                    .addComponent(jTexAddedAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsert)
                    .addComponent(jButtonSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddedNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddedNameMouseClicked

    }//GEN-LAST:event_jAddedNameMouseClicked

    private void jInsertAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertAction

          Connection conn=null;//make a connection with base/ command1!!!!
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/?user=root&password=root&allowPublicKeyRetrieval=true&useSSL=false");
        } catch (SQLException ex) {
            System.out.println("Cannot open connection " + ex.getMessage());
            return;
        }
        String name= jAddedName.getText();
        String age= jTexAddedAge.getText();
        
                 try{
    PreparedStatement st= conn.prepareStatement("Insert into persons (name, age) Values (?,?");//command2!!!! create statement
    // st.executeUpdate("CREATE DATABASE db");//create database
    st.executeUpdate("USE db");//use only this database
   //st.executeUpdate("CREATE TABLE persons (name varchar(64),age varchar(64))");//create table
     st.executeUpdate("Insert into persons (name, age) Values ('"+name+"', '"+age+"')");
       ResultSet rs= st.executeQuery("SELECT * FROM persons WHERE name='"+name+"' and age ='"+age+"'");
 
        while(rs.next()){//result of work 
    jTextArea1.append(rs.getString(1)+ "\n");
    jTextArea1.append(rs.getString(2)+ "\n");
  
    }
    
  }
                  catch(SQLException ex){
      System.out.println(ex.getMessage());
      } 
  
    }//GEN-LAST:event_jInsertAction

    private void jAddedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddedNameActionPerformed
        jAddedName.setText(""); 
    }//GEN-LAST:event_jAddedNameActionPerformed

    private void jTexAddedAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexAddedAgeActionPerformed
        jTexAddedAge.setText("");
    }//GEN-LAST:event_jTexAddedAgeActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
  
          Connection conn=null;//make a connection with base/ command1!!!!
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/?user=root&password=root&allowPublicKeyRetrieval=true&useSSL=false");
        } catch (SQLException ex) {
            System.out.println("Cannot open connection " + ex.getMessage());
            return;
        }
        
        String name= jAddedName.getText();
        String age= jTexAddedAge.getText();
        
                 try{
    PreparedStatement st= conn.prepareStatement("Insert into persons (name, age) Values (?,?");//command2!!!! create statement
    // st.executeUpdate("CREATE DATABASE db");//create database
    st.executeUpdate("USE db");//use only this database
   //st.executeUpdate("CREATE TABLE persons (name varchar(64),age varchar(64))");//create table
     //st.executeUpdate("Insert into persons (name, age) Values ('"+name+"', '"+age+"')");
    //ResultSet rs= st.executeQuery("SELECT * FROM persons ORDER BY name");// исполняем запрос

   ResultSet rs= st.executeQuery("SELECT * FROM persons WHERE name='"+name+"' and age ='"+age+"'");
        while(rs.next()){//result of work 
    jTextArea2.append(rs.getString(1)+ "\n");
    jTextArea2.append(rs.getString(2)+ "\n");
  
    }
    
  }
                  catch(SQLException ex){
      System.out.println(ex.getMessage());
      } 
   
    }//GEN-LAST:event_jButtonSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDBFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddName;
    private javax.swing.JLabel jAddedAge;
    private javax.swing.JTextField jAddedName;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTexAddedAge;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
